[package]
name = "co-acvm"
version = "0.1.0"
publish.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
acir.workspace = true
acvm.workspace = true
ark-bn254.workspace = true
ark-ff.workspace = true
eyre.workspace = true
intmap.workspace = true
mpc-core.workspace = true
noirc-abi.workspace = true
noirc-artifacts.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
paste.workspace = true
