[package]
name = "poseidon_input2"
type = "bin"
authors = [""]
compiler_version = ">=0.33.0"

[dependencies]
poseidon = { tag = "v0.2.0", git = "https://github.com/TaceoLabs/noir-poseidon", directory = "poseidon" }
