[package]
name = "ultrahonk"
version = "0.4.0"
publish.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
acir.workspace = true
ark-bn254.workspace = true
ark-ec.workspace = true
ark-ff.workspace = true
co-builder = { version = "0.3.0", path = "../co-builder" }
mpc-core = { version = "0.8.0", path = "../../mpc-core" }
eyre.workspace = true
itertools.workspace = true
noirc-artifacts.workspace = true
num-bigint.workspace = true
serde_json.workspace = true
sha3 = { workspace = true }
tracing.workspace = true

[dev-dependencies]
rand.workspace = true
