[package]
name = "ultrahonk"
version = "0.1.0"
publish.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
acir.workspace = true
ark-ec.workspace = true
ark-ff.workspace = true
ark-serialize.workspace = true
ark-bn254.workspace = true
byteorder.workspace = true
eyre.workspace = true
itertools.workspace = true
lazy_static = "1.5"
noirc-artifacts.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
serde_json.workspace = true
tracing.workspace = true
thiserror.workspace = true

[dev-dependencies]
rand.workspace = true
