[package]
name = "ultrahonk"
version = "0.7.0"
publish.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ark-ec.workspace = true
ark-ff.workspace = true
co-noir-common = { version = "0.3.0", path = "../co-noir-common" }
noir-types = { version = "0.1.2", path = "../noir-types" }
mpc-core = { version = "0.11.0", path = "../../mpc-core" }
ark-poly.workspace = true
eyre.workspace = true
itertools.workspace = true
num-bigint.workspace = true
tracing.workspace = true
rand.workspace = true
rand_chacha.workspace = true

[dev-dependencies]
rand.workspace = true
