[package]
name = "co-noir"
version = "0.3.0"

publish.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acir.workspace = true
ark-bn254.workspace = true
ark-ec.workspace = true
ark-ff.workspace = true
bincode.workspace = true
clap.workspace = true
co-acvm = { version = "0.3.0", path = "../co-acvm" }
co-ultrahonk = { version = "0.2.0", path = "../co-ultrahonk" }
color-eyre.workspace = true
figment.workspace = true
mpc-core = { version = "0.6.0", path = "../../mpc-core" }
mpc-net = { version = "0.2.0", path = "../../mpc-net" }
noirc-abi.workspace = true
rand.workspace = true
rustls.workspace = true
serde_json.workspace = true
serde.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing.workspace = true
sha3.workspace = true
