[package]
name = "noir-types"
version = "0.1.2"
publish.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ark-bn254.workspace = true
ark-ff = { workspace = true }
acir.workspace = true
noirc-abi.workspace = true
noirc-artifacts.workspace = true
eyre = { workspace = true }
co-noir-types = { version = "0.1.2", path = "../co-noir-types" }
ruint = { workspace = true }
serde_json = { workspace = true }
toml.workspace = true
num-bigint.workspace = true

[dev-dependencies]
