[package]
name = "poseidon"
type = "bin"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
poseidon = { tag = "v0.4.0", git = "https://github.com/TaceoLabs/noir-poseidon", directory = "poseidon" }
